### ISSUE TITLE
Add support for some or all of Airflow's "Documentation and notes"

### ISSUE THREAD

**Issue by dossett** [etsy/boundary-layer#1]
https://airflow.apache.org/concepts.html#documentation-notes

**Comment by everglory99** [comment]
I think #26 adds support for that, you can write `doc_md` in `dag_args` in the YAML file.

**Comment by dossett** [comment]
Terrific @everglory99 I will test this out!

**Comment by dossett** [comment]
@everglory99 I confirmed this does work, thanks for the contribution!
