### ISSUE TITLE
Input schema documentation

### ISSUE THREAD

**Issue by freuk** [etsy/boundary-layer#32]
Do you provide documentation for external users on the behavior of json schema entries from
[boundary_layer/schemas/dag.py](boundary_layer/schemas/dag.py)? Thanks.

**Comment by mchalek** [comment]
hi @freuk sorry, documentation is definitely a problem for us right now.  However the JSON schema entries are generally copied verbatim into arguments passed to operators in the rendered DAGs.  There are occasional transformations that we perform when necessary, e.g. turning integers into `datetime` values when necessary.  Does this help?  Please let me know if you have any more specific questions, or general areas on which you would like more clarity.  I don't have a lot of time to devote to this project at the moment, but I would like to do a better job of documenting it eventually.

**Comment by freuk** [comment]
I don't have any specific questions on the format, but the additional context is helpful.  Thanks for your reply!
