### ISSUE TITLE
[Question] What are the best practices when passing non-primitive types as arguments to operators?

### ISSUE THREAD

**Issue by codesue** [etsy/boundary-layer#38]
What are the best practices when passing non-primitive types as arguments to operators? Is doing so currently supported in boundary-layer?

**Comment by codesue** [comment]
I found an answer to this in a different issue: https://github.com/etsy/boundary-layer/issues/23#issuecomment-483868453
> The only way to define functions in boundary-layer at this time is by using string-valued parameters, and supplying those parameters as `verbatim strings` in the dag (meaning strings that are enclosed by the delimiters `<<` and `>>`, which get pasted directly into the generated python code).

**Comment by mchalek** [comment]
Oh, great!  Glad that you were able to find the solution @codesue .  Let us know if there's anything else we can help with!

**Comment by codesue** [comment]
Thanks for following up, @mchalek! Incidentally, I'm trying to figure out how to use custom templates instead of `primary_preamble.j2` and `operator.j2` to create a DAG using a context manager and to change the indentation of the operators accordingly. Currently, I've hard-coded the names of my custom templates in place of the standard templates. Are custom templates supported in boundary-layer?

**Comment by codesue** [comment]
@mchalek Apparently using a context manager makes it more convenient to write DAGs since it's not necessary to write `dag = dag` in all operators, but this is inconsequential when using boundary-layer. That said, I still think custom templates would be a great feature. I'm interested in contributing this, but I'm using boundary-layer as part of my intern project, so I'd need to get feedback and approval before I can commit to doing so.
