### ISSUE TITLE
Add support in EmailOperator

### ISSUE THREAD

**Issue by peleyal** [etsy/boundary-layer#80]
The existing operators list (https://github.com/etsy/boundary-layer/tree/master/boundary_layer_default_plugin/config/operators) there is no support in an `EmailOperator` (https://airflow.apache.org/docs/stable/_modules/airflow/operators/email_operator.html).

This PR is for adding the required support in `EmailOperator`.

**Comment by peleyal** [comment]
I'm going to add a new email_operator.html following other examples. Hopefully a PR will be ready by EOD.

Thanks!

**Comment by peleyal** [comment]
OK.. This might sound stupid but I cloned (using both SSH and HTTPS) the repo and have a local commit, however when I try to push it and create a PR I get the following:
* Using ssh:
```
remote: Permission to etsy/boundary-layer.git denied to peleyal.
fatal: unable to access 'https://github.com/etsy/boundary-layer.git/': The requested URL returned error: 403
```
* Using https:
```
ERROR: Permission to etsy/boundary-layer.git denied to peleyal.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What am I missing? (note that I am able to push to my enterprise repo)
@mchalek I saw your name around other PRs... Do you have any idea?

Thanks!

**Comment by dossett** [comment]
@peleyal You will need to fork the repo (i.e. make your own copy of it) and then create a PR from the fork back to this main repo.  Hope that helps!

**Comment by peleyal** [comment]
Super helpful! Thanks so much 👍 
https://github.com/etsy/boundary-layer/pull/81

**Comment by peleyal** [comment]
Friendly ping...
Can someone please take a look at the PR?
Thank you!

**Comment by dossett** [comment]
@peleyal Thank you for the contribution! I will try to look this week but am fairly busy with (appropriately!) a production Airflow upgrade.

**Comment by peleyal** [comment]
Thanks for the update! I believe it should be simple.
